apiVersion: v1
kind: Secret
metadata:
  name: {{ include "travel-share.fullname" . }}
  labels:
    {{- include "travel-share.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
    django-secret-key: {{ .Values.django.secretKey | b64enc | quote }}
    sql-username: {{ .Values.sql.username | b64enc | quote }}
    sql-password: {{ .Values.sql.password | b64enc | quote }}