apiVersion: v1
kind: Service
metadata:
  name: {{ include "travel-share.fullname" . }}
  labels:
    {{- include "travel-share.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "travel-share.selectorLabels" . | nindent 4 }}
