apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "travel-share.fullname" . }}
  labels:
    {{- include "travel-share.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  - "*"
  gateways:
  - travel-share
  http:
  - match:
    - uri:
        prefix: /admin
    - uri:
        prefix: /rest-auth
    - uri:
        prefix: /api
    - uri:
        prefix: /static
    route:
    - destination:
        port:
          number: 8000
        host: {{ include "travel-share.fullname" . }}
