apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: clouddns
spec:
  acme:
    email: shiftry123@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: clouddns-pk
    solvers:
    - dns01:
        cloudDNS:
          project: augmented-ward-272221