apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: travel-share
  namespace: travel-share
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"